import type { Campaign, CommunityPost } from "./types";

// 현재 시각 기준 N일 뒤 ISO 문자열
function inDays(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString();
}

const img = (seed: string, w = 800, h = 600) =>
  `https://picsum.photos/seed/${seed}/${w}/${h}`;

// DB 연결 전에도 사이트가 살아있게 보이도록 하는 데모 캠페인.
// Supabase 연결 + 시드 후에는 실제 데이터로 대체됨.
export const SAMPLE_CAMPAIGNS: Campaign[] = [
  {
    id: "demo-1",
    advertiser_id: null,
    title: "강남 프리미엄 오마카세 디너 2인 체험",
    type: "visit",
    category: "맛집",
    channels: ["blog", "instagram"],
    region: "서울",
    thumbnail_url: img("omakase"),
    images: [img("omakase"), img("omakase2"), img("omakase3")],
    offer: "15만원 상당 오마카세 디너 코스 2인",
    reward_point: 0,
    offer_value: 150000,
    description:
      "신선한 제철 재료로 구성된 강남 최고급 오마카세를 무료로 체험해보세요. 셰프가 직접 제공하는 16코스 디너입니다.",
    mission: "방문 후기 사진 15장 이상 + 본문 1,000자 이상, 지정 키워드 3개 포함",
    keywords: ["강남오마카세", "강남맛집", "오마카세추천"],
    recruit_count: 2,
    apply_start: inDays(-3),
    apply_end: inDays(2),
    announce_at: inDays(3),
    review_end: inDays(17),
    address: "서울 강남구 테헤란로 123",
    status: "open",
    is_premium: true,
    view_count: 1243,
    applicant_count: 58,
    favorite_count: 92,
    created_at: inDays(-3),
  },
  {
    id: "demo-2",
    advertiser_id: null,
    title: "유기농 콜드프레스 주스 30병 정기배송 체험",
    type: "delivery",
    category: "식품",
    channels: ["blog", "instagram", "reels"],
    region: "전국",
    thumbnail_url: img("juice"),
    images: [img("juice"), img("juice2")],
    offer: "12만원 상당 콜드프레스 주스 30병",
    reward_point: 0,
    offer_value: 120000,
    description:
      "착즙 원액 100% 콜드프레스 주스를 집에서 받아보고 솔직한 후기를 남겨주세요.",
    mission: "블로그 후기 + 인스타 릴스 1건, 음용 장면 필수",
    keywords: ["콜드프레스", "다이어트주스", "유기농주스"],
    recruit_count: 20,
    apply_start: inDays(-5),
    apply_end: inDays(6),
    announce_at: inDays(7),
    review_end: inDays(21),
    address: null,
    status: "open",
    is_premium: true,
    view_count: 2310,
    applicant_count: 134,
    favorite_count: 201,
    created_at: inDays(-5),
  },
  {
    id: "demo-3",
    advertiser_id: null,
    title: "제주 오션뷰 풀빌라 1박 2일 숙박권",
    type: "visit",
    category: "여행/숙박",
    channels: ["blog", "instagram", "youtube"],
    region: "제주",
    thumbnail_url: img("villa"),
    images: [img("villa"), img("villa2"), img("villa3")],
    offer: "35만원 상당 오션뷰 풀빌라 1박",
    reward_point: 50000,
    offer_value: 350000,
    description:
      "제주 서귀포 오션뷰 프라이빗 풀빌라에서의 하룻밤. 조식 포함, 추가 포인트 5만원 지급.",
    mission: "유튜브 또는 블로그 후기 1건 + 인스타 피드 2건",
    keywords: ["제주풀빌라", "제주숙소", "오션뷰"],
    recruit_count: 3,
    apply_start: inDays(-1),
    apply_end: inDays(9),
    announce_at: inDays(10),
    review_end: inDays(30),
    address: "제주 서귀포시 중문관광로 72",
    status: "open",
    is_premium: true,
    view_count: 4021,
    applicant_count: 287,
    favorite_count: 512,
    created_at: inDays(-1),
  },
  {
    id: "demo-4",
    advertiser_id: null,
    title: "비건 수분크림 신제품 체험단",
    type: "delivery",
    category: "뷰티",
    channels: ["blog", "instagram"],
    region: "전국",
    thumbnail_url: img("cream"),
    images: [img("cream"), img("cream2")],
    offer: "6.8만원 상당 수분크림 정품 + 샘플 키트",
    reward_point: 0,
    offer_value: 68000,
    description: "민감성 피부를 위한 저자극 비건 수분크림. 2주 사용 후기를 남겨주세요.",
    mission: "before/after 사진 + 블로그 후기 800자 이상",
    keywords: ["비건화장품", "수분크림추천", "민감성피부"],
    recruit_count: 50,
    apply_start: inDays(-2),
    apply_end: inDays(0),
    announce_at: inDays(1),
    review_end: inDays(18),
    address: null,
    status: "open",
    is_premium: false,
    view_count: 1876,
    applicant_count: 423,
    favorite_count: 188,
    created_at: inDays(-2),
  },
  {
    id: "demo-5",
    advertiser_id: null,
    title: "성수동 감성 브런치 카페 2인 방문",
    type: "visit",
    category: "맛집",
    channels: ["instagram", "reels"],
    region: "서울",
    thumbnail_url: img("brunch"),
    images: [img("brunch"), img("brunch2")],
    offer: "5만원 상당 브런치 세트 2인",
    reward_point: 0,
    offer_value: 50000,
    description: "성수동 핫플 브런치 카페. 시그니처 메뉴 2인 세트를 체험하세요.",
    mission: "인스타 피드 1건 + 릴스 1건, 매장 위치 태그 필수",
    keywords: ["성수동카페", "브런치맛집", "성수맛집"],
    recruit_count: 10,
    apply_start: inDays(-4),
    apply_end: inDays(1),
    announce_at: inDays(2),
    review_end: inDays(16),
    address: "서울 성동구 연무장길 45",
    status: "open",
    is_premium: false,
    view_count: 980,
    applicant_count: 76,
    favorite_count: 64,
    created_at: inDays(-4),
  },
  {
    id: "demo-6",
    advertiser_id: null,
    title: "무선 노이즈캔슬링 이어폰 페이백 체험",
    type: "payback",
    category: "디지털/가전",
    channels: ["blog", "youtube"],
    region: "전국",
    thumbnail_url: img("earbuds"),
    images: [img("earbuds"), img("earbuds2")],
    offer: "구매 후 전액 페이백 (89,000원)",
    reward_point: 89000,
    offer_value: 89000,
    description:
      "자사몰에서 직접 구매 후 후기 작성 시 구매가 전액을 페이백해드립니다.",
    mission: "구매 인증 + 블로그 상세 리뷰 + 유튜브 언박싱",
    keywords: ["노이즈캔슬링", "무선이어폰추천", "가성비이어폰"],
    recruit_count: 15,
    apply_start: inDays(-6),
    apply_end: inDays(4),
    announce_at: inDays(5),
    review_end: inDays(25),
    address: null,
    status: "open",
    is_premium: false,
    view_count: 3120,
    applicant_count: 211,
    favorite_count: 340,
    created_at: inDays(-6),
  },
  {
    id: "demo-7",
    advertiser_id: null,
    title: "반려견 수제 간식 정기구독 체험단",
    type: "delivery",
    category: "반려동물",
    channels: ["blog", "instagram"],
    region: "전국",
    thumbnail_url: img("dogtreat"),
    images: [img("dogtreat")],
    offer: "4.5만원 상당 수제간식 3종 세트",
    reward_point: 0,
    offer_value: 45000,
    description: "100% 휴먼그레이드 재료로 만든 반려견 수제 간식.",
    mission: "반려견 시식 사진 10장 + 블로그 후기",
    keywords: ["강아지간식", "수제간식", "반려견"],
    recruit_count: 30,
    apply_start: inDays(-2),
    apply_end: inDays(7),
    announce_at: inDays(8),
    review_end: inDays(22),
    address: null,
    status: "open",
    is_premium: false,
    view_count: 720,
    applicant_count: 51,
    favorite_count: 39,
    created_at: inDays(-2),
  },
  {
    id: "demo-8",
    advertiser_id: null,
    title: "홈트레이닝 스마트 거울 신제품 기자단",
    type: "press",
    category: "디지털/가전",
    channels: ["blog", "youtube"],
    region: "전국",
    thumbnail_url: img("mirror"),
    images: [img("mirror"), img("mirror2")],
    offer: "59만원 상당 스마트 홈트 거울 (체험 후 반납)",
    reward_point: 100000,
    offer_value: 590000,
    description:
      "AI 자세 분석 홈트레이닝 거울. 전문 기자단으로 심층 리뷰를 작성합니다.",
    mission: "장기 사용 리뷰 2건 + 유튜브 영상 1건, 포인트 10만원 지급",
    keywords: ["홈트레이닝", "스마트미러", "홈짐"],
    recruit_count: 5,
    apply_start: inDays(0),
    apply_end: inDays(12),
    announce_at: inDays(13),
    review_end: inDays(45),
    address: null,
    status: "open",
    is_premium: true,
    view_count: 1530,
    applicant_count: 33,
    favorite_count: 110,
    created_at: inDays(0),
  },
];

export const SAMPLE_POSTS: CommunityPost[] = [
  {
    id: "post-1",
    author_id: null,
    author_nickname: "리뷰왕초보",
    category: "체험단 후기",
    title: "첫 방문형 체험단 당첨됐어요! 후기 작성 팁 공유합니다",
    content:
      "블로그 개설 2주차에 처음 당첨됐습니다. 사진은 최소 15장, 키워드는 제목과 본문에 자연스럽게 넣는 게 중요하더라고요.",
    view_count: 1204,
    comment_count: 23,
    created_at: inDays(-1),
  },
  {
    id: "post-2",
    author_id: null,
    author_nickname: "맛집헌터",
    category: "꿀팁",
    title: "경쟁률 낮은 체험단 고르는 법 (당첨률 3배 올리기)",
    content:
      "신규 등록 + 마감임박 + 모집인원 많은 캠페인을 노리면 당첨 확률이 확 올라갑니다. 매칭점수 높은 순으로 정렬해서 신청하세요.",
    view_count: 3421,
    comment_count: 67,
    created_at: inDays(-2),
  },
  {
    id: "post-3",
    author_id: null,
    author_nickname: "인플루언서지망생",
    category: "질문",
    title: "인스타 팔로워 몇 명부터 체험단 신청하는 게 좋을까요?",
    content: "팔로워 500명인데 신청해도 될까요? 다들 어느 정도에서 시작하셨나요?",
    view_count: 890,
    comment_count: 41,
    created_at: inDays(-3),
  },
];
